-- Entités simples

CREATE TABLE REFUGE (
   EMAIlREF VARCHAR(50) PRIMARY KEY,
   NOM VARCHAR(50),
   NUMTEL INT,
   SECGEO VARCHAR(50),
   DATEOUV DATE,
   DATEFERME DATE,
   NBrREPAS INT,
   NBrPLACEsDORMIR INT,
   TEXTE VARCHAR(50),
   TYPePAYEMENT VARCHAR(20),
   PRIxNUITE DECIMAL,
   PRIX DECIMAL
);

CREATE TABLE REPAS (
   TYPeRepas VARCHAR(20)
);

CREATE TABLE RESERVATION_REFUGE (
   ID INT PRIMARY KEY,
   DATE_RESERVATION DATE,
   HEURE INT,
   NBrNUITS INT,
   NBrREPAsRESERVE INT,
   PRIxTOTAL DECIMAL,
   EMAIlREF REFERENCES REFUGE(EMAIlREF), -- Cardinalité 1..1
   IdUSER REFERENCES COMPTE_UTILISATEUR(IdUSER) -- Cardinalité 1..1
);

CREATE TABLE COMPTE_UTILISATEUR (
   IdUSER INT PRIMARY KEY,
   COUtRESERV DECIMAL,
   SOMMeMATERIElABIME DECIMAL,
   SOMMeREMBOURSEE DECIMAL
);

CREATE TABLE MEMBRE (
   EMAIlMEMBRE VARCHAR(50) PRIMARY KEY,
   MDP VARCHAR(20),
   NOM VARCHAR(20),
   PRENOM VARCHAR(20),
   ADrPOST VARCHAR(30),
   IdUSER REFERENCES COMPTE_UTILISATEUR(IdUSER) -- Cardinalité 1..1
);

CREATE TABLE RESERVATION_FORMATION (
   ID INT PRIMARY KEY,
   RANGRESERVFORM INT,
   IdUSER REFERENCES COMPTE_UTILISATEUR(IdUSER) -- Cardinalité 1..1
   IdFORM REFERENCES FORMATION(IdFORM), -- Cardinalité 1..1
   ANNEeFORM REFERENCES FORMATION(ANNEeFORM) -- Cardinalité 1..1
);

CREATE TABLE FORMATION (
   IdFORM INT,
   ANNEeFORM DATE,
   PRIMARY KEY (NUMERO, ANNEE),
   NOM VARCHAR(50),
   DATeDEM DATE,
   DUREE INT,
   NBrPLACE INT,
   DESC VARCHAR(50),
   PRIX DECIMAL,
   NBrACTIVITE INT
);

CREATE TABLE ACTIVITE (
   NOmACTIVITE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE LOT (
   MARQUE VARCHAR(20),
   MODELE VARCHAR(20),
   ANNEeACHAT DATE,
   PRIMARY KEY(MARQUE, MODELE, ANNEeACHAT),
   NbPIECES INT,
   PRIxPERTE INT,
   TEXTeOPT VARCHAR(100),
   ANNEePEREMPTION DATE,
   CATEGORIE REFERENCES ARBRE(CATEGORIE) -- Cardinalité 1..1
);

CREATE TABLE ARBRE (
   CATEGORIE VARCHAR(30) PRIMARY KEY
);

CREATE TABLE LOCATION_MATERIEL (
   ID INT PRIMARY KEY,
   NbPIECEsRESERV INT,
   DATeRECUP DATE,
   DATeRETOUR DATE, 
   NbPIECEsPERDUES INT
   MARQUE REFERENCES LOT(MARQUE), -- Cardinalité 1..1
   MODELE REFERENCES LOT(MODELE), -- Cardinalité 1..1
   ANNEeACHAT REFERENCES LOT(ANNEeACHAT), -- Cardinalité 1..1
   IdUSER REFERENCES COMPTE_UTILISATEUR(IdUSER) -- Cardinalité 1..1
);


-- Sous-types d'entité


-- Duplication
CREATE TABLE ADHERENT (
   EMAIlMEMBRE VARCHAR(50) REFERENCES MEMBRE(EMAIlMEMBRE) PRIMARY KEY,
   MDP VARCHAR(20),
   NOM VARCHAR(20),
   PRENOM VARCHAR(20),
   ADrPOST VARCHAR(30),
   IdAdherent INT
);


-- Cardinalité 1..1
   
-- SOUsCATEGORIE (ARBRE) -> (LOT)
-- EMAIlREF (REFUGE) -> (RESERVATION_REFUGE)
-- IdUSER (COMPTE_UTILISATEUR) -> (RESERVATION_REFUGE)
-- IdUSER (COMPTE_UTILISATEUR) -> (RESERVATION_FORMATION)
-- IdUSER (COMPTE_UTILISATEUR) -> (LOCATION_MATERIEL)
-- IdUSER (COMPTE_UTILISATEUR) -> (MEMBRE)
-- MARQUE, MODELE, ANNEeACHAT (LOT) -> (LOCATION_MATERIEL)
-- IdFORM, ANNEeFORM (FORMATION) -> (RESERVATION_FORMATION)


-- Cardinalité 0..1

CREATE TABLE EST_ENFANT_DE (
   CATEGORIeENFANT REFERENCES ARBRE(CATEGORIE) PRIMARY KEY,
   CATEGORIePARENT REFERENCES ARBRE(CATEGORIE)
);


-- Cardinalité ?..*

CREATE TABLE PROPOSE_REPAS (
   EMAIlREF REFERENCES REFUGE(EMAIlREF),
   TYPeREPAS REFERENCES REPAS(TYPeREPAS),
   PRIMARY KEY (EMAIL, TYPeREPAS),
   PRIxREPAS DECIMAL
);

CREATE TABLE RESERVE_REPAS (
   IdRERSERvREF REFERENCES RESERVATION_REFUGE(IdRESERvREF),
   TYPeREPAS REFERENCES REPAS(TYPeREPAS),
   PRIMARY KEY (IdRERSERvREF, TYPeREPAS),
   NbREPAsRESERVE INT
);

CREATE TABLE PROPOSE_ACTIVITE_FORM (
   IdFORM REFERENCES FORMATION(IdFORM),
   ANNEeFORM REFERENCES FORMATION(ANNEeFORM),
   NOmACTIVITE REFERENCES ACTIVITE(NomACTIVITE),
   PRIMARY KEY (NUMERO, ANNEE, NOmACTIVITE)
);

CREATE TABLE COMPATIBLE_AVEC_ACTIVITE (
   MARQUE REFERENCES LOT(MARQUE),
   MODELE REFERENCES LOT(MODELE),
   ANNEeACHAT REFERENCES LOT(ANNEeACHAT),
   NOmACTIVITE REFERENCES ACTIVITE(NomACTIVITE),
   PRIMARY KEY (MARQUE, MODELE, ANNEeACHAT, NOmACTIVITE)
);
   
   
   





























   
   

    
