------------------------ Compte USER : -----------------------------


CREATE TABLE COMPTE_UTILISATEUR 
(
   IdUSER INT PRIMARY KEY,
   COUtRESERV DECIMAL,
   SOMMeMATERIElABIME DECIMAL,
   SOMMeREMBOURSEE DECIMAL
);






CREATE TABLE MEMBRE (
   EMAIlMEMBRE VARCHAR(50) PRIMARY KEY,
   MDP VARCHAR(20),
   NOM VARCHAR(20),
   PRENOM VARCHAR(20),
   ADrPOST VARCHAR(30),
   IdUSER INT , 
   FOREIGN KEY(IdUSER) REFERENCES COMPTE_UTILISATEUR(IdUSER) -- Cardinalité 1..1
);





CREATE TABLE ADHERENT 
(
    IdADHERENT INT PRIMARY KEY,
    EMAIlMEMBRE VARCHAR(50),
    MDP VARCHAR(20),
    NOM VARCHAR(50), 
    PRENOM VARCHAR(50),
    ADrPOST VARCHAR(50),
    IdUSER INT,
    FOREIGN KEY(IdUSER) REFERENCES COMPTE_UTILISATEUR(IdUSER) , 
    FOREIGN KEY(EMAIlMEMBRE ) REFERENCES  MEMBRE(EMAIlMEMBRE ) 

);


