@startuml
Participant "Client" as C
Participant "Système" as S
Participant "Base de donnée" as B
hide footbox

C -> S : crereCompte(username, Password)
activate S

S -> B : creat(username, Password)
activate B

B --> S : erreur : le compte existe déjà
deactivate B

S --> C : erreur : le compte existe déjà
deactivate S
@enduml